# pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "t_arp"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.10.0",
    "jaxlib>=0.10.0",
    "equinox",
    "chex",
    "tqdm",
    "numpy",
    "pandas",
    "Pillow",
    "yuvio",
    "fastparquet",
    "pyarrow",
    "matplotlib",
    "matplot2tikz",
    "Jinja2",
    "PyYAML"
]
